openapi: 3.0.0
info:
  title: Unsupervised Machine Learning using (Cloudmesh Cloud AI Services Services)
  description: Unsupervised Machine Learning using Cloudmesh Cloud AI Services
  license:
    name: Apache 2.0
  version: 0.0.2
  servers:
  - url: http://localhost:8000/project
  paths:
  /file/upload:
    post:
      summary: csv data file upload to server
      operationId: project.file.upload
      requestBody:
        description: file to be uploaded by end-user
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: sample file has been uploaded successfully
          content:
              application/json:
                schema:
                  type: object
                  properties:
                    file_name:
                      type: string
      /kmeans:
        post:
          summary: predict on a previously built model
          operationId: project.kmeans_calc
          requestBody:
            content:
              multipart/form-data:
                schema:
                  type: object
                  properties:
                    job_id:
                      type: string
                    file:
                      type: string
                      format: binary
          responses:
            '200':
              description: successful completion
              content:
                text/csv:
                  schema:
                    type: string
                    format: binary
